import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "#fff",
    flex: 1,
  },
  containerCadastro:{
    backgroundColor: "#fff",
    flex: 1,
    justifyContent: 'space-between',
  },
  containerLoad: {
    justifyContent: "center",
    backgroundColor: "#fff",
    flex: 1,
  },
  textCircle: {
    textAlign: "center",
    fontSize: 14,
    marginTop: 55,
    marginRight: 30,
    marginLeft: 15,
  },
  circle: {
    borderRadius: 50,
    backgroundColor: "white",
    height: 60,
    width: 60,
    borderWidth: 2,
    borderColor: "#00298F",
    marginLeft: 35,
    marginTop: 35,
    justifyContent: "center",
  },
  circle2: {
    borderRadius: 50,
    backgroundColor: "#000",
    height: 48,
    width: 48,
    alignSelf: "center",
  },
  bigCircle: {
    borderRadius: 100,
    backgroundColor: "white",
    height: 200,
    width: 200,
    borderWidth: 2,
    borderColor: "#00298F",
    marginTop: 30,
    justifyContent: "center",
  },
  bigCircle2: {
    borderRadius: 100,
    backgroundColor: "#000",
    height: 185,
    width: 185,
    alignSelf: "center",
  },
  vaiVexImg: {
    resizeMode: "contain",
    alignSelf: "center",
    marginVertical: 40,
  },
  vaiVexImgCadastro: {
    resizeMode: "contain",
    alignSelf: "center",
    marginTop: 40,
    marginBottom: 20,
  },
  firstImg: {
    resizeMode: "contain",
    alignSelf: "flex-start",
    bottom: 15,
  },
  retanguloAzul: {
    backgroundColor: "#00298F",
    width: '65%',
    height: 400,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  retanguloAzul1: {
    backgroundColor: "#00298F",
    width: '65%',
    height: 310,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  retanguloVermelho1: {
    backgroundColor: "#ED1C24",
    width: '65%',
    height: 310,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  loginText: {
    textAlign: "left",
    fontSize: 18,
    fontFamily: "Bariol_Regular_0",
    color: "#fff",
    marginLeft: 20,
    marginBottom: 25,
    width: 150,
  },
  btnCadastrar: {
    backgroundColor: "#fff",
    padding: 15,
    borderColor: "#000",
    borderWidth: 2,
    borderRadius: 10,
    marginHorizontal: 30,
    alignItems: "center",
    marginBottom: 20,
  },
  btnCadastrarFont: {
    fontSize: 18,
    color: "#000",
  },
  wrapper: {},
  retanguloVermelho: {
    backgroundColor: "#ED1C24",
    width: '65%',
    height: 400,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  textBox: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginBottom: 10,
    flexDirection: "row",
  },
  textBox1: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginBottom: 60,
    flexDirection: "row",
  },
  textBox2: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    bottom: 40,
    flexDirection: "row",
  },
  textBox30: {
    backgroundColor: "#fff",
    height: 45,
    borderColor: "#656565",
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 10,
    width: 90,
    marginLeft: 30,
    flexDirection: "row",
  },
  textBox70: {
    backgroundColor: "#fff",
    height: 45,
    borderColor: "#3B3B3B",
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 10,
    width: 225,
    marginLeft: 20,
    flexDirection: "row",
  },
  box3070: {
    flexDirection: "row",
    flex: 1,
  },
  textBoxFont: {
    fontSize: 14,
    textAlign: "left",
    marginLeft: 10,
    color: "#656565",
    minWidth: '75%',
    maxWidth: '75%',
  },
  textBoxDesc: {
    fontSize: 14,
    textAlign: "left",
    marginLeft: 10,
    color: "#656565",
    minWidth: '95%',
    maxWidth: '95%',
  },
  textBoxFontCadastro: {
    fontSize: 14,
    textAlign: "left",
    marginLeft: 10,
    top: 13,
    color: "#656565",
  },
  btnComecar: {
    backgroundColor: "#00298F",
    padding: 15,
    borderRadius: 5,
    marginHorizontal: 30,
    alignItems: "center",
    marginVertical: 20,
  },
  btnComecarFont: {
    fontSize: 16,
    color: "#fff",
  },
  redCircle: {
    backgroundColor: "#ED1C24",
    borderRadius: 300,
    width: 240,
    height: 240,
    justifyContent: "center",
    alignSelf: "center",
    position: "absolute",
    right: 50,
    bottom: 20,
    alignItems: "center",
    alignContent: "center",
  },
  blueCircle: {
    backgroundColor: "#00298F",
    borderRadius: 300,
    width: 240,
    height: 240,
    alignSelf: "center",
    position: "absolute",
    right: 50,
    justifyContent: "center",
    marginTop: 70,
    alignItems: "center",
    alignContent: "center",
  },
  porcentagemLoad: {
    fontSize: 72,
    color: "#fff",
  },
  textLoad: {
    fontSize: 24,
    marginHorizontal: 35,
    top: 200,
    marginTop: 35,
    textAlign: "center",
    color: "#000",
  },
  btnReady: {
    backgroundColor: "#00298F",
    padding: 15,
    borderRadius: 5,
    marginHorizontal: 30,
    alignItems: "center",
    top: 200,
    marginTop: 45,
  },
  retanguloAzulHome: {
    backgroundColor: "#00298F",
    width: '85%',
    height: 230,
    borderRadius: 10,
    marginLeft: 30,
    marginTop: 30,
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
  },
  retanguloAzulPag: {
    backgroundColor: "#00298F",
    width: '80%',
    minHeight: 200,
    borderRadius: 7,
    marginTop: 30,
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
    alignSelf: 'center',
    flex: 1,
  },
  textRetanguloHome: {
    fontSize: 26,
    color: "#fff",
    textAlign: "center",
  },
  imgHome: {
    resizeMode: "contain",
    alignSelf: "center",
  },
  grayBox: {
    backgroundColor: "#DCDCDC",
    width: "85%",
    height: 100,
    alignSelf: "center",
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 30,
    flexDirection: "row",
    justifyContent: 'space-around',
  },
  grayBoxBigText: {
    fontSize: 50,
    color: "#000",
    marginLeft: 25,
  },
  grayBoxSmallText: {
    color: "#000",
    fontSize: 14,
    marginLeft: 25,
    bottom: 10,
    maxWidth: 80,
  },
  btnAdmin: {
    backgroundColor: "#346CFF",
    borderRadius: 5,
    alignItems: "center",
    width: "32%",
    height: 29,
    alignSelf: "center",
    marginHorizontal: 10,
    justifyContent: "center",
  },
  btnAdminFont: {
    fontSize: 14,
    color: "#fff",
    alignSelf: "center",
    elevation: 5,
    textAlign: "center",
  },
  procurarBox: {
    width: "90%",
    height: 80,
    backgroundColor: "#00298F",
    marginHorizontal: 10,
    borderRadius: 10,
    alignSelf: "center",
    bottom: 270,
    justifyContent: "center",
  },
  procurarContainer: {
    flexDirection: "column-reverse",
    justifyContent: "flex-end",
    opacity: 0.55,
  },
  procurarBox2: {
    width: "90%",
    height: 100,
    backgroundColor: "#00298F",
    marginHorizontal: 10,
    borderRadius: 10,
    marginBottom: 30,
    alignSelf: "center",
    bottom: 492,
    justifyContent: "center",
  },
  circleProcurar: {
    borderRadius: 50,
    backgroundColor: "#00298F",
    height: 54,
    width: 54,
    borderWidth: 2,
    borderColor: "#fff",
    justifyContent: "center",
    marginLeft: 20,
  },
  circle2Procurar: {
    borderRadius: 50,
    backgroundColor: "#000",
    height: 40,
    width: 40,
    alignSelf: "center",
  },
  whiteLineHorizontal: {
    backgroundColor: "#fff",
    width: "92%",
    height: 1,
    alignSelf: "center",
  },
  whiteLineVertical: {
    backgroundColor: "#fff",
    width: 1,
    height: "96%",
    alignSelf: "center",
  },
  blackLineHorizontal: {
    backgroundColor: "#656565",
    width: "90%",
    height: 1,
    alignSelf: "center",
    marginVertical: 20,
  },
  nameText: {
    fontSize: 12,
    color: "white",
    alignSelf: "center",
    maxWidth: 50,
    marginHorizontal: 10,
  },
  procurarFont: {
    fontSize: 12,
    color: "white",
    textAlign: "left",
    marginLeft: 10,
    marginVertical: 10,
  },
  horarioFont: {
    fontSize: 20,
    color: "white",
    textAlign: "center",
    marginLeft: 12,
    marginTop: 5,
  },
  horarioFont1: {
    fontSize: 10,
    color: "white",
    textAlign: "center",
    marginLeft: 12,
  },
  circleText: {
    color: "white",
    alignSelf: "center",
    fontSize: 26,
    textAlign: "center",
  },
  textBoxChamar: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 10,
    flexDirection: "row",
  },
  textBoxGuardar: {
    backgroundColor: "#ECECEC",
    height: 50,
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 10,
    flexDirection: "row",
  },
  blueBtn: {
    backgroundColor: "#346CFF",
    width: 135,
    height: 50,
    marginLeft: 30,
    marginRight: 30,
    alignSelf: "center",
    borderRadius: 5,
    marginVertical: 25,
    justifyContent: "center",
  },
  greenBtn: {
    backgroundColor: "#00AA33",
    width: "85%",
    height: 60,
    marginHorizontal: 15,
    alignSelf: "center",
    borderRadius: 5,
    justifyContent: "center",
    marginBottom: 40,
  },
  motoboyText: {
    fontSize: 20,
    color: "#fff",
    alignSelf: "center",
    elevation: 5,
    textAlign: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    margin: 20,
    backgroundColor: "#00298F",
    borderRadius: 5,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 7,
  },
  buttonLeft: {
    width: 135,
    height: 50,
    alignSelf: "center",
    borderRadius: 5,
    marginLeft: "8%",
    justifyContent: "center",
  },
  buttonRight: {
    width: 135,
    height: 50,
    alignSelf: "center",
    borderRadius: 5,
    justifyContent: "center",
  },
  buttonOpen: {
    backgroundColor: "#346CFF",
  },
  buttonClose: {
    backgroundColor: "white",
    borderRadius: 3,
    width: 45,
    height: 30,
    margin: 10,
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  textStyleClose: {
    color: "#00298F",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 20,
  },
  modalText: {
    marginTop: 30,
    textAlign: "center",
    color: "white",
  },
  enderecoStyle: {
    textAlign: "center",
    fontSize: 22,
    color: "white",
    marginHorizontal: 11,
  },
  dotStyle: {
    backgroundColor: "rgba(0,0,0,.2)",
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  textPagamento:{
    fontSize: 12,
    color: 'black',
    marginTop: 65,
    marginRight: 30,
    marginLeft: 5,
    flex:1,
  },
  greenPag:{
    width: '85%',
    minHeight: 40,
    maxHeight: 60,
    alignSelf: 'center',
    justifyContent: 'center',
    backgroundColor: '#00AA33',
    marginBottom: 30,
    borderRadius: 7,
    flex: 1,
  },
  grayBoxConc:{
    width: '90%',
    height: 120,
    justifyContent: 'center',
    alignContent: 'center',
    backgroundColor: '#DCDCDC',
    borderRadius: 8,
    flexDirection: 'row',
    marginVertical: 20,
  },
  textSettings:{
    fontSize: 14,
    textAlign: 'left',
    marginLeft: 30,
    marginTop: 50,
  },
  switchBtn: {
    alignSelf: "flex-start",
    marginLeft: 30,
    marginTop: 15,
    marginBottom: 20,
  },
  textBoxFontContato: {
    fontSize: 14,
    textAlign: "left",
    marginLeft: 20,
    top: 13,
    color: "#656565",
  },
  textBoxContato: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginTop: 20,
    flexDirection: "row",
  },
  textBoxContatoDesc: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 150,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginTop: 20,
  },
  blueBtnEnviar:{
    backgroundColor: '#346CFF',
    height: 40,
    width: '85%',
    marginHorizontal: 30,
    marginTop: 15,
    justifyContent: 'center',
    alignContent: 'center',
    borderRadius: 6,
  },
  textSobre:{
    fontSize: 12,
    marginLeft: 30,
  },
  bigCircleCond: {
    borderRadius: 100,
    backgroundColor: "white",
    height: 150,
    width: 150,
    borderWidth: 2,
    borderColor: "#00298F",
    marginTop: 30,
    justifyContent: "center",
    marginLeft: 30,
  },
  bigCircleCond2: {
    borderRadius: 100,
    backgroundColor: "#000",
    height: 135,
    width: 135,
    alignSelf: "center",
  },
  redBox:{
    width: '38%',
    height: 35,
    alignSelf: 'flex-end',
    marginRight: 15,
    backgroundColor: '#346CFF',
    borderRadius: 6,
    justifyContent: 'center',
  },
  blueBox:{
    width: '38%',
    height: 35,
    marginLeft: 15,
    alignSelf: 'flex-start',
    backgroundColor: '#ED1C24',
    borderRadius: 6,
    justifyContent: 'center',
  },
  textCondutorBtn:{
    fontSize: 14,
    color: 'white',
    textAlign: 'center',
  },
});
