import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#fff",
  },
  containerLoad: {
    justifyContent: "center",
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#fff",
  },
  textCircle: {
    textAlign: "center",
    fontSize: 14,
    marginTop: 50,
    marginRight: 50,
    marginLeft: 10,
  },
  circle: {
    borderRadius: 50,
    backgroundColor: "white",
    height: 60,
    width: 60,
    borderWidth: 2,
    borderColor: "#00298F",
    marginLeft: 35,
    marginTop: 35,
    justifyContent: "center",
  },
  circle2: {
    borderRadius: 50,
    backgroundColor: "#000",
    height: 48,
    width: 48,
    alignSelf: "center",
  },
  vaiVexImg: {
    resizeMode: "contain",
    alignSelf: "center",
    marginTop: 15,
  },
  firstImg: {
    resizeMode: "contain",
    alignSelf: "flex-start",
    bottom: 15,
  },
  retanguloAzul: {
    backgroundColor: "#00298F",
    width: 256,
    height: 400,
    marginTop: 30,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  retanguloAzul1: {
    backgroundColor: "#00298F",
    width: 256,
    height: 340,
    marginTop: 30,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  retanguloVermelho1: {
    backgroundColor: "#ED1C24",
    width: 256,
    height: 340,
    marginTop: 30,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  loginText: {
    textAlign: "left",
    fontSize: 18,
    fontFamily: "Bariol_Regular_0",
    color: "#fff",
    marginLeft: 20,
    marginBottom: 25,
    width: 150,
  },
  btnCadastrar: {
    backgroundColor: "#fff",
    padding: 15,
    borderColor: "#000",
    borderWidth: 2,
    borderRadius: 10,
    marginHorizontal: 30,
    alignItems: "center",
    marginBottom: 20,
  },
  btnCadastrarFont: {
    fontSize: 18,
    color: "#000",
  },
  wrapper: {},
  retanguloVermelho: {
    backgroundColor: "#ED1C24",
    width: 256,
    height: 400,
    marginTop: 30,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: "column-reverse",
  },
  textBox: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginBottom: 10,
    flexDirection: "row",
  },
  textBox1: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginBottom: 60,
    flexDirection: "row",
  },
  textBox2: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    bottom: 40,
    flexDirection: "row",
  },
  textBox30: {
    backgroundColor: "#fff",
    height: 50,
    borderColor: "#656565",
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 10,
    width: 110,
    marginLeft: 30,
    flexDirection: "row",
  },
  textBox70: {
    backgroundColor: "#fff",
    height: 50,
    borderColor: "#3B3B3B",
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 10,
    width: 200,
    marginLeft: 20,
    flexDirection: "row",
  },
  box3070: {
    flexDirection: "row",
  },
  textBoxFont: {
    fontSize: 14,
    textAlign: "left",
    marginLeft: 10,
    color: "#656565",
    width: 300,
    maxWidth: 175,
  },
  textBoxFontCadastro: {
    fontSize: 14,
    textAlign: "left",
    marginLeft: 10,
    top: 13,
    color: "#656565",
  },
  btnComecar: {
    backgroundColor: "#00298F",
    padding: 15,
    borderRadius: 5,
    marginHorizontal: 30,
    alignItems: "center",
    marginTop: 45,
  },
  btnComecarFont: {
    fontSize: 16,
    color: "#fff",
  },
  redCircle: {
    backgroundColor: "#ED1C24",
    borderRadius: 300,
    width: 240,
    height: 240,
    justifyContent: "center",
    alignSelf: "center",
    position: "absolute",
    right: 50,
    bottom: 20,
  },
  blueCircle: {
    backgroundColor: "#00298F",
    borderRadius: 300,
    width: 240,
    height: 240,
    alignSelf: "center",
    position: "absolute",
    right: 50,
    justifyContent: "center",
    marginTop: 70,
  },
  porcentagemLoad: {
    fontSize: 72,
    color: "#fff",
    top: 70,
    left: 40,
  },
  textLoad: {
    fontSize: 24,
    marginHorizontal: 35,
    top: 200,
    marginTop: 35,
    textAlign: "center",
    color: "#000",
  },
  btnReady: {
    backgroundColor: "#00298F",
    padding: 15,
    borderRadius: 5,
    marginHorizontal: 30,
    alignItems: "center",
    top: 200,
    marginTop: 45,
  },
  retanguloAzulHome: {
    backgroundColor: "#00298F",
    width: 268,
    height: 212,
    borderRadius: 10,
    marginLeft: 30,
    marginTop: 30,
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
  },
  textRetanguloHome: {
    fontSize: 26,
    color: "#fff",
    textAlign: "center",
    bottom: 10,
    right: 2,
  },
  imgHome: {
    resizeMode: "contain",
    alignSelf: "center",
  },
  grayBox: {
    backgroundColor: "#DCDCDC",
    width: "85%",
    height: 100,
    alignSelf: "center",
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 40,
    flexDirection: "row",
  },
  grayBoxBigText: {
    fontSize: 50,
    color: "#000",
    marginLeft: 25,
  },
  grayBoxSmallText: {
    color: "#000",
    fontSize: 14,
    marginLeft: 25,
    bottom: 10,
  },
  btnAdmin: {
    backgroundColor: "#346CFF",
    borderRadius: 5,
    alignItems: "center",
    width: 115,
    height: 29,
    alignSelf: "center",
    marginLeft: 10,
    justifyContent: "center",
  },
  btnAdminFont: {
    fontSize: 14,
    color: "#fff",
    alignSelf: "center",
    elevation: 5,
    textAlign: "center",
  },
  procurarBox: {
    width: "90%",
    height: 80,
    backgroundColor: "#00298F",
    marginHorizontal: 10,
    borderRadius: 10,
    marginVertical: 10,
    alignSelf: "center",
    bottom: 270,
    justifyContent: "center",
  },
  procurarContainer: {
    flexDirection: "column-reverse",
    justifyContent: "flex-end",
    opacity: 0.55,
  },
  procurarBox2: {
    width: "90%",
    height: 100,
    backgroundColor: "#00298F",
    marginHorizontal: 10,
    borderRadius: 10,
    marginVertical: 10,
    alignSelf: "center",
    bottom: 492,
    justifyContent: "center",
  },
  circleProcurar: {
    borderRadius: 50,
    backgroundColor: "#00298F",
    height: 54,
    width: 54,
    borderWidth: 2,
    borderColor: "#fff",
    justifyContent: "center",
    marginLeft: 20,
  },
  circle2Procurar: {
    borderRadius: 50,
    backgroundColor: "#000",
    height: 40,
    width: 40,
    alignSelf: "center",
  },
  whiteLineHorizontal: {
    backgroundColor: "#fff",
    width: "92%",
    height: 1,
    alignSelf: "center",
  },
  whiteLineVertical: {
    backgroundColor: "#fff",
    width: 1,
    height: "96%",
    alignSelf: "center",
  },
  blackLineHorizontal: {
    backgroundColor: "#656565",
    width: "90%",
    height: 1,
    alignSelf: "center",
    marginVertical: 20,
  },
  nameText: {
    fontSize: 12,
    color: "white",
    alignSelf: "center",
    maxWidth: 50,
    marginHorizontal: 10,
  },
  procurarFont: {
    fontSize: 12,
    color: "white",
    textAlign: "left",
    marginLeft: 10,
    marginVertical: 10,
  },
  horarioFont: {
    fontSize: 20,
    color: "white",
    textAlign: "center",
    marginLeft: 12,
    marginTop: 5,
  },
  horarioFont1: {
    fontSize: 10,
    color: "white",
    textAlign: "center",
    marginLeft: 12,
  },
  circleText: {
    color: "white",
    alignSelf: "center",
    fontSize: 26,
    textAlign: "center",
  },
  textBoxChamar: {
    backgroundColor: "#fff",
    borderColor: "#656565",
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 10,
    flexDirection: "row",
  },
  textBoxGuardar: {
    backgroundColor: "#ECECEC",
    height: 50,
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 10,
    flexDirection: "row",
  },
  blueBtn: {
    backgroundColor: "#346CFF",
    width: 135,
    height: 50,
    marginLeft: 30,
    marginRight: 30,
    alignSelf: "center",
    borderRadius: 5,
    marginVertical: 25,
    justifyContent: "center",
  },
  greenBtn: {
    backgroundColor: "#00AA33",
    width: "85%",
    height: 60,
    marginHorizontal: 15,
    alignSelf: "center",
    borderRadius: 5,
    marginTop: 50,
    justifyContent: "center",
  },
  motoboyText: {
    fontSize: 20,
    color: "#fff",
    alignSelf: "center",
    elevation: 5,
    textAlign: "center",
  },
});
