import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  containerLoad: {
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  circle: {
    borderRadius: 50,
    backgroundColor: 'white',
    height: 55,
    width: 55,
    borderWidth: 3,
    borderColor: '#3a3967',
    marginLeft: 35,
    marginTop: 35,
  },
  circle2: {
    borderRadius: 50,
    backgroundColor: '#3a3967',
    height: 44,
    width: 44,
    top: 2,
    left: 2,
  },
  vaiVexImg: {
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: 20,
  },
  firstImg:{
    resizeMode: 'contain',
    alignSelf: 'flex-start',
    bottom: 15,
  },
  retanguloAzul: {
    backgroundColor: '#00298F',
    width: 256,
    height: 400,
    marginTop: 45,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: 'column-reverse',
  },
  loginText: {
    textAlign: 'left',
    fontSize: 18,
    fontFamily: 'Bariol_Regular_0',
    color: '#fff',
    marginLeft: 20,
    marginBottom: 25,
    width: 150,
  },
  btnCadastrar: {
    backgroundColor: '#fff',
    padding: 15,
    borderColor: '#000',
    borderWidth: 3,
    borderRadius: 10,
    marginHorizontal: 30,
    alignItems: 'center',
    marginBottom: 30,
  },
  btnCadastrarFont: {
    fontSize: 18,
    color: '#000',
  },
  wrapper: {},
  retanguloVermelho: {
    backgroundColor: '#ED1C24',
    width: 256,
    height: 400,
    marginTop: 45,
    borderRadius: 10,
    marginLeft: 30,
    flexDirection: 'column-reverse',
  },
  textBox: {
    backgroundColor: '#fff',
    borderColor: '#3B3B3B',
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 30,
    marginTop: 10,
    flexDirection: 'row',
  },
  textBox30: {
    backgroundColor: '#fff',
    height: 50,
    borderColor: '#3B3B3B',
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 10,
    width: 110,
    marginLeft: 30,
    flexDirection: 'row',
  },
  textBox70: {
    backgroundColor: '#fff',
    height: 50,
    borderColor: '#3B3B3B',
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 10,
    width: 200,
    marginLeft: 20,
    flexDirection: 'row',
  },
  box3070:{
    flexDirection: 'row',
  },
  textBoxFont: {
    fontSize: 16,
    textAlign: 'left',
    marginLeft: 10,
    color: '#656565',
    width: 300,
  },
  textBoxFontCadastro: {
    fontSize: 16,
    textAlign: 'left',
    marginLeft: 10,
    top: 13,
    color: '#656565',
  },
  btnComecar: {
    backgroundColor: '#00298F',
    padding: 15,
    borderRadius: 5,
    marginHorizontal: 30,
    alignItems: 'center',
    marginTop: 45,
  },
  btnComecarFont:{
    fontSize: 16,
    color: '#fff',
  },
  redCircle:{
    backgroundColor: '#ED1C24',
    borderRadius: 300,
    width: 240,
    height: 240,
    alignSelf: 'center',
    position: 'absolute',
    bottom: 30,
    right: 50,
  },
  blueCircle:{
    backgroundColor: '#00298F',
    borderRadius: 300,
    width: 240,
    height: 240,
    alignSelf: 'center',
    position: 'absolute',
    right: 50,
  },
  porcentagemLoad:{
    fontSize: 72,
    color: '#fff',
    top: 70,
    left: 40,
  },
  textLoad:{
    fontSize: 24,
    marginHorizontal: 35,
    top: 200,
    textAlign: 'center',
    color: '#000',
  },
})